spring.application.name=fintech-be

server.port=8080

logging.level.dev.ctrlspace.fintech2506=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.root=INFO

spring.datasource.url=jdbc:postgresql://localhost:5433/fintech
spring.datasource.username=fintech
spring.datasource.password=${DATABASE_PASSWORD:fintech}

#llms.groq.key=${GROQ_API_KEY:12345}
llms.openai.key=${OPEN_AI_KEY:12345}
